#!/bin/bash

bspc config border_width        1
bspc config window_gap          11

bspc config split_ratio         0.5
bspc config borderless_monocle  false
bspc config gapless_monocle     false
bspc config focus_by_distance   true

#bspc monitor -d 1 2 3 4 5
bspc monitor -d 1 2 3 4
bspc rule -a uk-ac-starlink-topcat-Driver state=floating

bspc config normal_border_color '#1d1f21'
bspc config focused_border_color '#c5c8c6'
bspc config presel_border_color '#b5bd68'
bspc config normal_sticky_border_color '#8abeb7'
bspc config focused_sticky_border_color '#f0c674'
bspc config urgent_border_color '#cc6666'

~/.config/bspwm/panel &
