#!/bin/bash
#
# bar input parser for bspwm

NORMIFS=$IFS
FIELDIFS=':'

source $(dirname $0)/panel_config

while read -r line ; do
    case $line in
        S*)
            # conky
            sys_infos="${line#?}"
            ;;
        #M*)
        #    spotify="${line#?}"
        #    ;;
        #C*)
            ##clock
            #clock="${line#?}"
            #clock="%{F$CLOCK_BG}⮂%{F- B$CLOCK_BG A:dzen_popup_toggle.sh calendar:} ${clock} %{A B- F$CLOCK_BG}⮀%{F-}"
            #;;
        T*)
            if [[ ${line#?} == "" ]]; then
                title=""			
	    else 
        	#title="%{F$WHITE_COLOR}$(printf "%b" "\ue0b1")%{F} %{F$GRAY1_COLOR}%{A:bspc node -t floating:}${line#?}%{F}%{A}"
      		title="%{F$WHITE_COLOR}$(printf "%b" " \ue1a4")%{F} %{F$GRAY1_COLOR}${line#?}%{F}"

            fi
          ;;
        W*)
            wm_infos=""
            IFS=$FIELDIFS
            set -- ${line#?}
            while [ $# -gt 0 ] ; do
                item=$1
                case $item in
                    [OoFfUu]*)
                        name=${item#?}
                        case $name in
                    #1) DESK_ICON="$(printf '%b' "\ue1ef")" ;;
                    1) DESK_ICON="$(printf "%b" "\ue174")" ;;
		            2) DESK_ICON="$(printf "%b" "\ue175")" ;;
		            3) DESK_ICON="$(printf "%b" "\ue176")" ;;
  		            4) DESK_ICON="$(printf "%b" "\ue177")" ;;
		            5) DESK_ICON="$(printf "%b" "\ue178")" ;;
                        esac
                        case $item in
                            O*)
                                # focused occupied desktop
                                desk="%{F$COLOR2} $DESK_ICON %{F-}"
                                ;;
                            F*)
                                # focused free desktop
                                desk="%{F$COLOR2} $DESK_ICON %{F-}"
                                ;;
                            U*)
                                # focused urgent desktop
                                desk="%{F$WHITE_COLOR} $DESK_ICON %{F-}"
                                ;;
                            o*)
                                # occupied desktop
                                desk="%{F$WHITE_COLOR} $DESK_ICON %{F-}"
                                ;;
                            f*)
                                # free desktop
                                desk="%{F$GRAY2_COLOR} $DESK_ICON %{F-}"
                                ;;
                            u*)
                                # urgent desktop
                                desk="%{F$COLOR1} $DESK_ICON %{F-}"
                                ;;
                        esac
                        wm_infos="${wm_infos}%{A:bspc desktop -f ${name}:}${desk}%{A}"
                        ;;
                    [L]*)
             		#if [[ ${item#?} == "T" ]]; then
                         #   layout="%{F$FOREGROUND_COLOR B$YELLOW2_COLOR A:bspc desktop -l monocle: A3:bspc desktop -R 90:}  $(printf "%b" "\ue131")  %{A A B F-}"
                        #else
		       	layout="%{F$GRAY1_COLOR B$GRAY1_COLOR A:bspc node -t tiled:} $(printf "%b" "\ue1ce") %{A B F-}"
                        #fi
                        ;;
                esac
                shift
            done
            IFS=$NORMIFS
            ;;
    esac
    printf "%s\n" "%{c B$FOREGROUND_COLOR}$wm_infos %{B-} $SEP %{l O:22}$title $sys_infos"
done
